// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4T0CBwHa5cjOVh_tfW-mQMKX35U0PyU8',
    appId: '1:570116337890:web:95cb2f9ee6ec46f2342ebb',
    messagingSenderId: '570116337890',
    projectId: 'fluenteer-e6a47',
    authDomain: 'fluenteer-e6a47.firebaseapp.com',
    storageBucket: 'fluenteer-e6a47.firebasestorage.app',
    measurementId: 'G-BCR6XDVB8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqQp_ZKwV-cFNoUzALotmjlTiiQvs8lvo',
    appId: '1:570116337890:android:ef99f584356fa66c342ebb',
    messagingSenderId: '570116337890',
    projectId: 'fluenteer-e6a47',
    storageBucket: 'fluenteer-e6a47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6x2v4cPCD52t7cOEdIRBXSFB7VDMKers',
    appId: '1:570116337890:ios:afc3b44970e80b79342ebb',
    messagingSenderId: '570116337890',
    projectId: 'fluenteer-e6a47',
    storageBucket: 'fluenteer-e6a47.firebasestorage.app',
    iosBundleId: 'com.example.fluenteer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6x2v4cPCD52t7cOEdIRBXSFB7VDMKers',
    appId: '1:570116337890:ios:afc3b44970e80b79342ebb',
    messagingSenderId: '570116337890',
    projectId: 'fluenteer-e6a47',
    storageBucket: 'fluenteer-e6a47.firebasestorage.app',
    iosBundleId: 'com.example.fluenteer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4T0CBwHa5cjOVh_tfW-mQMKX35U0PyU8',
    appId: '1:570116337890:web:a275ea0ac770f2d4342ebb',
    messagingSenderId: '570116337890',
    projectId: 'fluenteer-e6a47',
    authDomain: 'fluenteer-e6a47.firebaseapp.com',
    storageBucket: 'fluenteer-e6a47.firebasestorage.app',
    measurementId: 'G-QXSWX6E07J',
  );
}
